### ISSUE TITLE
Workflow - Agregar el workflow de GH para la generacion de release

### ISSUE THREAD

**Issue by embesozzi** [rakkau/email-notify-authentication-node#2]
Agregar el workflow de release y generacion de jar.

- Cree un main branch y lo puse como default.

**Comment by embesozzi** [comment]
@ezeqsifo cuando puedas tocas el readme sacando todo lo de Forgerock y solo dejamos lo que hicimos nosotros. Parecido a como lo deje el readme del custom para el node assessment de Google

**Comment by ezeqsifo** [comment]
Se subieron esos cambios a [other/maven-workflow](https://github.com/rakkau/email-notify-authentication-node/tree/other/maven-workflow)

Igual que en el repo de external handler node, se debe configurar en el repositorio: **Settings > Secret and Variables > Actions > Secrets** los siguientes secretos:

- FRUSERNAME: usuario de forgerock
- FRPASSWORD: hash de password de forgerock
- CHAT_WEBHOOK_URL: url de webhook de google chat
